title: Manitoba Highland Gathering
description: 'Saturday, July 2-3, 2016<br>Legacy Park, East Selkirk<br>R.M. of St. Clements<br>HWY 59 and PR # 212<br>located behind the East Selkirk Recreational Centre<br>PR#212 and Strathcona Road'
caption: 50th Annual
logo: manitoba-highland-gathering.png
map_url: https://plus.google.com/app/basic/110733743294538783083/about?gl=ca&hl=en&source=appredir
disqus_shortname:
search: false
# Change url to your domain. Leave localhost server or blank when working locally.
# url: http://www.manitobahighlandgathering.org
url: http://localhost:3500
port: 3500

# Owner/author information
owner:
  name:           Manitoba Highland Gathering
  email:          mbhighlandgathering@gmail.com
  # Social networking links used in footer. Update and remove as you like.
  twitter: MBGathering
  facebook: pages/Manitoba-Highland-Gathering/153072571473587

# Analytics and webmaster tools stuff goes here
google_analytics:
google_verify:
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Links to include in top navigation
# For external links add external: true
links:
  - title: Home
    url: /
  - title: Events &amp; Schedule
    url: /schedule/
  - title: Photos
    url: /photos/
  - title: Tickets
    url: /tickets/
  - title: Forms
    url: /forms/
  - title: Friends
    url: /friends/
  - title: Local Attractions
    url: /local-attractions/
  - title: About Us
    url: /about-us/
  - title: Contact
    url: /contact/

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:    America/Winnipeg
future:      true
highlighter: true
markdown:    kramdown

# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink:   /:categories/:title/

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false

  coderay:
    coderay_line_numbers:
    coderay_line_numbers_start: 1
    coderay_tab_width: 4
    coderay_bold_every: 10
    coderay_css: class

include: [".htaccess"]
exclude: ["lib", "config.rb", "Gemfile", "Capfile", "Gemfile.lock", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules"]
